version: "3.7"
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    environment:
      RABBITMQ_ERLAND_COOKIE: "secret cookie"
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 10s
      timeout: 10s
      retries: 5

  server:
    container_name: server
    build:
      context: .
      dockerfile: ./deployments/server.Dockerfile
    ports:
      - "5001:5001"
    restart: on-failure
    environment:
      - AMQP_RABBIT_URL="amqp://rabbitmq:5672"
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    command: >
      /bin/sh -c "
        echo Waiting for rabbitmq service start...;
        while ! nc -z rabbitmq 5672;
        do
          sleep 1;
        done;
        echo Connected!;
        cd server && npm start
      "

  evt_server:
    container_name: evt_server
    build:
      context: .
      dockerfile: ./deployments/evt_server.Dockerfile
    ports:
      - "5000:5000"
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - AMQP_RABBIT_URL="amqp://rabbitmq:5672"
    command: >
      /bin/sh -c "
        echo Waiting for rabbitmq service start...;
        while ! nc -z rabbitmq 5672;
        do
          sleep 1;
        done;
        echo Connected!;
        cd server && npm start
      "
